frontend/main/routes.py
from asyncio.windows_events import NULL
import base64
import io
import profile
from PIL import Image
from frontend.users.forms import (AddProjectForm)
from frontend import db
from ast import Pass
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user
from matplotlib.pyplot import table
from frontend import bcyrpt
from frontend.models import Users
from frontend.users.forms import (EditProfile, AddEventForm, RegistrationForm, LoginForm,SearchUserForm,Message)
import sqlite3
from frontend.users.forms import (AddProjectForm, CommentForm, EventRegisterForm,studentToSubmitProject)

from flask import Flask, render_template, url_for, flash, session,redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
import sqlite3
table_info={'1':["Student","student_name","student_email","student_password","student_id"],
            '2':["Organizer","organizer_name","organizer_email","organizer_password","organizer_id"],
            '3':["Sponsor","sponsor_name","sponsor_email","sponsor_password","sponsor_id"]
            }


def db_connection():
    conn = None
    try:
        conn = sqlite3.connect("identifier.sqlite")
    except sqlite3.error as e:
        print(e)
    return conn

def OrganizerDetail():
    conn = db_connection()
    cursor = conn.cursor()
    sql_query = '''SELECT * from Organizer'''
    cursor =cursor.execute(sql_query)
    organizerList=cursor.fetchall()
    orgDet=dict()
    for org in organizerList:
        orgDet[org[0]]=list(org[1:])
    return orgDet


def searchProject(ProjectTitle):
    conn = db_connection()
    cursor = conn.cursor()
    # tou=current_user.type_of_user
    sql_query = '''
    SELECT * FROM Project WHERE project_title = "{}"'''.format(ProjectTitle)
    cursor =cursor.execute(sql_query)
    return cursor.fetchall()   

def getProjectList(usr_det):
    conn = db_connection()
    cursor = conn.cursor()
    sql_query = '''SELECT * from ProjectLink WHERE student_id = {}'''.format(usr_det[0][0])
    cursor =cursor.execute(sql_query)
    projLinkDet=cursor.fetchall()
    if projLinkDet==[]:
        return []
    sql_query = '''SELECT * from Project WHERE project_id = {}'''.format(projLinkDet[0][0])
    cursor =cursor.execute(sql_query)
    return cursor.fetchall()    

def FollowUser(usr_det):
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    # tou=current_user.type_of_user
    sql_query = '''INSERT into Follow(follower_id,following_id) values ({},{})'''.format( usr_det[0][0], usr_id)
    cursor =cursor.execute(sql_query)
    conn.commit()

def isFollowed(usr_det):
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    # tou=current_user.type_of_user
    sql_query = '''SELECT * from Follow WHERE follower_id = {} AND following_id = {}'''.format(usr_det[0][0], usr_id)
    cursor =cursor.execute(sql_query)
    # conn.commit()
    # print(sql_query)
    return cursor.fetchall()    

def isSponsored():
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    # tou=current_user.type_of_user
    sql_query = '''SELECT event_id from Sponsorship WHERE sponsor_id = {} '''.format(usr_id)
    cursor =cursor.execute(sql_query)
    # conn.commit()
    print(sql_query)
    return cursor.fetchall()    

# Function to retrieve events from database
def GetEvents():
    conn = db_connection()
    cursor = conn.cursor()
    sql_query = '''
    SELECT * FROM Event;
    '''
    cursor=cursor.execute(sql_query)
    print(cursor)
    return cursor.fetchall()

def userDetails():
    conn = db_connection()
    cursor = conn.cursor()
    tou=current_user.type_of_user
    sql_query = '''
    SELECT * FROM {} WHERE {} = "{}"'''.format(table_info[tou][0],table_info[tou][2],current_user.email)
    cursor =cursor.execute(sql_query)
    return cursor.fetchall()

def userDetailsLike(id,tou):
    conn = db_connection()
    cursor = conn.cursor()
    sql_query = '''SELECT * FROM {} WHERE {} = {}'''.format(table_info[tou][0],table_info[tou][4],id)
    cursor =cursor.execute(sql_query)
    # print(cursor.fetchall())
    data=cursor.fetchall()
    print(data)
    return data

def getUserList(typeofuser,Searchuser):
    conn = db_connection()
    cursor = conn.cursor()
    # tou=current_user.type_of_user
    tou=typeofuser
    sql_query = '''
    SELECT * FROM {} WHERE {} = "{}"'''.format(table_info[tou][0],table_info[tou][1],Searchuser)
    cursor =cursor.execute(sql_query)
    
    return cursor.fetchall()

def getSponsorship(id):
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    # tou=current_user.type_of_user

    sql_query = '''INSERT into Sponsorship(sponsor_id,event_id) values ({},{})'''.format(usr_id,id)
    # print(sql_query)
    cursor =cursor.execute(sql_query)
    conn.commit()   

def getSponsorsList():
    conn=db_connection()
    cursor=conn.cursor()
    sql_query = '''
    SELECT * FROM Sponsor '''
    cursor =cursor.execute(sql_query)
    
    return cursor.fetchall()

def getStudentList():
    conn=db_connection()
    cursor=conn.cursor()
    sql_query = '''
    SELECT * FROM Student '''
    cursor =cursor.execute(sql_query)
    # print(cursor.fetchall())
    
    return cursor.fetchall()  

def sendMessage(to_id,msg):
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    # tou=current_user.type_of_user

    sql_query = '''INSERT into Message(user_id,user_msg ,to_id) values ({},"{}",{})'''.format(usr_id,msg,to_id)
    print(sql_query)
    cursor =cursor.execute(sql_query)
    conn.commit()      

# def userProjectDetails():
#     conn = db_connection()
#     cursor=conn.cursor()
#     sql_query ='''
    
#     '''

def getMessage(to_id):
    conn = db_connection()
    cursor = conn.cursor()
    usr_id = userDetails()[0][0]
    sql_query='''SELECT * from Message WHERE user_id = {} and to_id = {} UNION SELECT * from Message WHERE user_id ={} and  to_id = {}'''.format(usr_id,to_id,to_id,usr_id)
    # print(sql_query)
    cursor =cursor.execute(sql_query)
    ans =cursor.fetchall()
    # print(ans)
    return ans

  

def getOrganizerList():
    conn=db_connection()
    cursor=conn.cursor()
    sql_query = '''
    SELECT * FROM Organizer '''
    cursor =cursor.execute(sql_query)
    return cursor.fetchall()


main = Blueprint('main', __name__)
@main.route('/',methods=['GET','POST'])
@main.route('/home',methods=['GET','POST'])
def home():
    events=GetEvents()
    
    # print(current_user)
    formNew=SearchUserForm()
    return render_template('landing.html')


@main.route('/displayProjects/<int:pId>')
def displayProjects(pId):
    conn=db_connection()
    cursor=conn.cursor()
    sql_query ='''
    SELECT * FROM Project where project_id = {}
    '''.format(pId)
    cursor=cursor.execute(sql_query)
    formNew=SearchUserForm()
    prjDetails=cursor.fetchall()
    stdID=userDetails()[0][1]
    return render_template('project_revamp.html', prjDetails=prjDetails, stdID=stdID, formNew=formNew)



@main.route('/sendMsg/<int:to_id>/<string:personName>',methods=['GET','POST'])
def sendMsg(to_id,personName):
    formNew=SearchUserForm()
    form=Message()
    msg=form.message.data
    sendMessage(to_id,msg)
    msgList = getMessage(to_id)
    return render_template('inbox.html',formNew=formNew,to_id=to_id,form=form,msgList=msgList,personName=personName)

@main.route('/eventsList',methods=['GET','POST'])
def eventsList():
    events=GetEvents()
    org_det = OrganizerDetail()
    formNew=SearchUserForm()
    return render_template('event.html',formNew=formNew,events=events,org_det=org_det)

@main.route('/inbox/<int:to_id>/<string:personName>',methods=['GET','POST'])
def inbox(to_id,personName):
    formNew=SearchUserForm()
    form=Message()
    # msg=form.message.data
    # print(msg)
    # sendMessage(to_id,msg)
    msgList=getMessage(to_id)
    # print(msgList)
    return render_template('inbox.html',formNew=formNew,to_id=to_id,form=form,msgList=msgList,personName=personName)


@main.route('/sponsorList',methods=['GET','POST'])
def sponsorList():
    formNew=SearchUserForm()
    sponsors=getSponsorsList()
    return render_template('sponsors_list.html',sponsors=sponsors,formNew=formNew)



@main.route('/editProfile',methods=['GET','POST'])
def editProfile():
    formNew=SearchUserForm()
    form=EditProfile()
    if request.method=='POST':
        stud_name=form.stud_name.data
        stud_email=form.stud_email.data
        stud_des=form.stud_des.data
        stud_interest=form.stud_interest.data

        list_of_interest=stud_interest.split(",")
        conn = db_connection()
        cursor=conn.cursor()
        sql_query='''
        UPDATE Student 
        SET student_desc ="{}" WHERE student_id={}
        '''.format(stud_des,userDetails()[0][0])
        cursor.execute(sql_query)
       
        current_user.email=stud_email

        return redirect('/account')
    return render_template('edit_profile_form.html',formNew=formNew,form=form)

@main.route('/myProfile/<int:id>/<string:tou>',methods=['GET','POST'])
def myProfile(id,tou):
    #current_user = > type , id
    # print(tou)
    followStatus="Followed"
    usr_det=userDetailsLike(id,tou)
    pr = isFollowed(usr_det)
    ProjInfo=getProjectList(usr_det)
    if pr==[]:
        followStatus="Follow"
    # print(usr_det)
    # usr_det=[(1,2,3,4)]
    formNew=SearchUserForm()
    return render_template('profile.html',usr_det=usr_det,id=id,tou=tou,followStatus=followStatus,ProjInfo=ProjInfo,formNew=formNew)

@main.route('/eventsForSponsor',methods=['GET','POST'])
def eventsForSponsor():
    events=GetEvents()
    org_det = OrganizerDetail()
    formNew=SearchUserForm()
    eveSponsored = isSponsored()
    eveSp=list()
    for e in eveSponsored:
        eveSp.append(e[0])
    # print(eveSp)
    # if isSponsored(id)==[]:

frontend/templates/addEvent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Innov-8</title>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;700;900&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="../static/css/build.css" />
    <link rel="stylesheet" href="../static/css/login.css" />
</head>

<body>

    <div class="flex flex-col items-center justify-center min-h-screen p-4 space-y-4 antialiased text-gray-900">

        <a href="" class="inline-block mb-6 font-black tracking-wider uppercase text-5xl text-chamki-green-800">
            innov-8
        </a>

        <main>
            <div class="w-full max-w-sm px-4 py-6 space-y-6 bg-white rounded-md text-gray-700">
                <h1 class="text-xl font-semibold text-center">Register</h1>
                <form class="space-y-6" action="/addEvent" method="POST">
                    <div class="flex justify-evenly items-center text-lg font-light">
                        <label for="lang">Event Types</label>
                        {{ form.eventsdropdown()}}
                    </div> 
                    <label for="lang">Event Start Date</label>
                    {{ form.eventstartdate(placeholder="Event Start Date",class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:ring-sky-300")}}
                    <label for="lang">Event End Date</label>
                    {{ form.eventenddate(placeholder="Event End Date",class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:ring-sky-300")}}
                    <!-- <input class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:ring-sky-300"
                        type="text" name="email" placeholder="Username" required autocomplete="off" /> -->
                    {{ form.eventloc(placeholder="Event Location",class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:ring-sky-300")}}
                    {{ form.eventdec(placeholder="Event Description",class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring focus:ring-sky-300")}}
                    
                    <div>
                        {{ form.submit(class="w-full group [transform:translateZ(0)] px-6 py-3 rounded-lg  bg-info-light overflow-hidden relative before:absolute before:bg-info-dark before:bottom-0 before:left-0 before:h-full before:w-full before:origin-[100%_100%] before:scale-x-0 hover:before:origin-[0_0] hover:before:scale-x-100 before:transition before:ease-in-out before:duration-500 text-center") }}
                        <!-- <button type="submit"
                            class="w-full group [transform:translateZ(0)] px-6 py-3 rounded-lg  bg-info-light overflow-hidden relative before:absolute before:bg-info-dark before:bottom-0 before:left-0 before:h-full before:w-full before:origin-[100%_100%] before:scale-x-0 hover:before:origin-[0_0] hover:before:scale-x-100 before:transition before:ease-in-out before:duration-500 text-center">
                            <span
                                class="relative z-0 text-sky-100 group-hover:text-sky-100  transition ease-in-out duration-500 font-semibold">Register</span>
                        </button> -->
                    </div>
                </form>

                <div class="text-sm text-gray-600 dark:text-gray-400 flex items-center justify-evenly">
                    <p
                        class="group text-gray-600 transition duration-200 ease-in-out hover:text-fuchsia-800 font-medium hover:font-semibold">
                        Already have an account<span aria-hidden="true"
                            class="inline-block translate-x-0 transition-transform duration-200 ease-in-out group-hover:translate-x-1">?</span>
                    </p> <a href="/login"
                        class="relative text-blue-600 after:absolute after:bottom-0 after:left-0 after:h-[2px] after:w-full after:origin-bottom-right after:scale-x-0 after:bg-blue-400 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100">Login</a>
                </div>
            </div>
        </main>
    </div>

</body>

</html>

frontend/templates/edit_profile_form.html
{% extends "layout.html" %} {% block content %}
                <!-- Main content -->
                <div class="flex flex-col justify-around flex-1 h-full p-4">


                    <div class="w-full px-4 py-16 mx-auto sm:px-6 lg:px-8 mt-52">
                        <h1
                            class="text-2xl font-bold text-center text-indigo-600 sm:text-3xl relative after:absolute after:bg-indigo-600 after:bottom-[-5px] after:left-1/4 after:h-[2px] after:w-1/2 after:origin-bottom-left after:scale-x-100 hover:after:origin-bottom-right hover:after:scale-x-0 after:transition-transform after:ease-in-out after:duration-300">
                            Edit Profile
                        </h1>
                        <div class="max-w-lg mx-auto">


                            <form action="/editProfile" method="POST" class="p-8 mt-6 mb-0 space-y-4 rounded-lg shadow-2xl">


                                <div>
                                    <label for="title" class="text-sm font-medium">Name</label>

                                    <div class="relative mt-1">
                                        {{form.stud_name(placeholder="Display student name",class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm")}}
                                        <!-- <input type="text" id="title"
                                            class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm"
                                            placeholder="Display student name" /> -->
                                    </div>
                                </div>

                                <div>
                                    <label for="title" class="text-sm font-medium">Email</label>

                                    <div class="relative mt-1">
                                        {{form.stud_email(placeholder="Enter brief description about yourself",class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm")}}

                                        <!-- <input type="text" id="title"
                                            class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm"
                                            placeholder="Display student email " /> -->
                                    </div>
                                </div>

                                <div>
                                    <label for="shortdesc" class="text-sm font-medium">Brief Description</label>

                                    <div class="relative mt-1">
                                        {{form.stud_des(placeholder="Enter brief description about yourself",class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm")}}
                                        <!-- <input type="text" id="shortdesc"
                                            class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm"
                                            placeholder="Enter brief description about yourself" /> -->

                                    </div>
                                </div>

                                <!-- <div>
                                    <label for="drivelink" class="text-sm font-medium">Skills & Interests</label>

                                    <div class="relative mt-1">
                                        
                                        <input type="text" id="drivelink"
                                            class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm"
                                            placeholder="Add skills & interests here ( better if I make it dynamic)" />

                                    </div>
                                </div> -->

                                <div>
                                    <label for="interest" class="text-sm font-medium">Interests</label>

                                    <div class="relative mt-1">
                                        {{form.stud_interest(placeholder="Enter your Interest seperated by comma",class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm")}}
                                        <!-- <input type="text" id="shortdesc"
                                            class="w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm"
                                            placeholder="Enter brief description about yourself" /> -->

                                    </div>
                                </div>

                                <div class="relative group">
                                    <div
                                        class="absolute -inset-0.5 bg-gradient-to-r from-pink-600 to-purple-600 rounded-lg blur opacity-75 group-hover:opacity-100 transition duration-1000 group-hover:duration-200 animate-tilt">
                                    </div>

                                    <div class="relative bg-gray-200 text-black rounded-lg text-center">
                                        <!-- <button type="submit"
                                            class="block w-full px-5 py-3 text-sm font-medium text-white bg-indigo-500 rounded-lg">
                                            Submit 
                                        </button> -->
                                        {{form.submit(class="block w-full px-5 py-3 text-sm font-medium text-white bg-indigo-500 rounded-lg")}}
                                    </div>
                                </div>


                            </form>

                        </div>
                    </div>

                </div>

{% endblock content %}

frontend/templates/event.html
{% extends "layout.html" %} {% block content %}

                <!-- Main content -->
                
                <div class="flex p-4 flex-col">
                    <h1
                        class="text-2xl font-bold text-center text-indigo-600 sm:text-3xl relative after:absolute after:bg-indigo-600 after:bottom-[-5px] after:left-1/4 after:h-[2px] after:w-1/2 after:origin-bottom-left after:scale-x-100 hover:after:origin-bottom-right hover:after:scale-x-0 after:transition-transform after:ease-in-out after:duration-300 mb-10">
                        Explore events
                    </h1>
                    {% for event in events %}
                    <div class="relative p-8 overflow-hidden mb-10 border border-gray-100 rounded-lg bg-indigo-100"
                        href="">
                        <span
                            class="absolute inset-x-0 bottom-0 h-2  bg-gradient-to-r from-green-300 via-blue-500 to-purple-600">
                        </span>

                        <div class="justify-between  sm:flex">
                            <div>
                                <h5
                                    class="text-xl font-bold text-gray-900 p-3 mb-2 border-solid border-4 border-indigo-600 rounded-lg">
                                   {{ event[7] }}
                                </h5>

                            </div>

                            <div class="flex-shrink-0 hidden ml-3 sm:block  font-bold text-gray-900">
                                {{ event[3] }} - {{ event[4] }}
                            </div>
                        </div>

                        <div class="mt-4 sm:pr-8">

                            <p>

                            <p class="text-xl font-bold mb-4 text-gray-900">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block" fill="none"
                                    viewBox="0 0 24 24" stroke="green" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                                </svg>
                                Organized by : {{ org_det[event[2]][0] }}
                            </p>
                            <p class="mb-4">
                                {{ event[6] }}
                            </p>
                            <p class="font-bold text-gray-800 mb-6">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 inline-block" viewBox="0 0 20 20"
                                    fill="green">
                                    <path fill-rule="evenodd"
                                        d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z"
                                        clip-rule="evenodd" />
                                </svg>
                                {{ event[5] }}
                            </p>
                            <div class="flex items-center justify-around">
                            <form  class="flex w-full md:justify-start justify-center items-end" style="user-select: auto;" action="{{ url_for('main.registerForEvent',eventId=event[0] )}}">
                            <button
                                class="bg-green-700  justify-center hover:bg-green-800 text-white font-bold py-2 px-4 rounded">
                                Register
                            </button>
                            </form>
                            <form  class="flex w-full md:justify-start justify-center items-end" style="user-select: auto;" action="{{ url_for('main.eventDetailsForStudent',eventId=event[0] )}}">
                                <button
                                    class="bg-green-700  justify-center hover:bg-green-800 text-white font-bold py-2 px-4 rounded">
                                    View Details
                                </button>
                                </form>
                            </div>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                
                </div>
{% endblock %}

frontend/templates/harshdum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img alt="Embedded Image" src="data:image/png;base64,{{ image }}" />
</body>
</html>

frontend/templates/inbox.html
{% extends "layout.html" %}
{% block content %}
                <!-- Main content -->
                <div class="p-4">
                    <h1
                        class="text-2xl font-bold text-center text-indigo-600 sm:text-3xl relative after:absolute after:bg-indigo-600 after:bottom-[-5px] after:left-1/4 after:h-[2px] after:w-1/2 after:origin-bottom-left after:scale-x-100 hover:after:origin-bottom-right hover:after:scale-x-0 after:transition-transform after:ease-in-out after:duration-300 mb-10">
                        Chat with {{personName}}
                    </h1>
                    <div class="flex flex-col flex-grow w-full bg-white shadow-xl rounded-lg my-4">
                        <div class="flex flex-col flex-grow h-1/16 p-4 overflow-auto">
                            {% for msg in msgList %}
                            {% if msg[1] == to_id %}
                            <div class="flex w-full mt-2 space-x-3 max-w-xs">
                                <div>
                                    <div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">
                                        <p class="text-sm">{{msg[2]}} </p>
                                    </div>
                                </div>
                            </div> 
                            {% else %}
                            <div class="flex w-full mt-2 space-x-3 max-w-xs ml-auto justify-end">
                                <div>
                                    <div class="bg-blue-600 text-white p-3 rounded-l-lg rounded-br-lg">
                                        <p class="text-sm">{{msg[2]}}</p>
                                    </div>
                                </div>
                            </div>

                            {% endif %}
                            {% endfor %}
                            

                            <!-- <div class="flex w-full mt-2 space-x-3 max-w-xs ml-auto justify-end">
                                <div>
                                    <div class="bg-blue-600 text-white p-3 rounded-l-lg rounded-br-lg">
                                        <p class="text-sm">Lorem ipsum dolor sit.</p>
                                    </div>
                                </div>
                            </div> -->
                            <!-- <div class="flex w-full mt-2 space-x-3 max-w-xs">
                                <div>
                                    <div class="bg-gray-300 p-3 rounded-r-lg rounded-bl-lg">
                                        <p class="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                                            do eiusmod tempor
                                            incididunt ut labore et dolore magna aliqua. </p>
                                    </div>
                                </div>
                            </div> -->

                        </div>

                        <div class="bg-gray-300 p-4 flex justify-between w-full items-center">
                            <!-- <input class= type="text"
                                placeholder="Type your message…"> -->
                                <form action="{{ url_for('main.sendMsg',to_id=to_id,personName=personName) }}" class="space-y-6" method="POST">  
                                {{ form.message(class="flex items-center h-10 w-full rounded px-3 text-sm",placeholder="Type your message…") }}
                            <!-- <button
                                class="inline-block p-3 text-white bg-indigo-600 border border-indigo-600 rounded-full hover:bg-transparent hover:text-indigo-600 active:text-indigo-500 focus:outline-none focus:ring ml-4"
                                href="{{ url_for('main.home') }}">
                                <span class="sr-only"> Download </span> -->
                                {{ form.submit(class="inline-block p-3 text-white bg-indigo-600 border border-indigo-600 rounded-full hover:bg-transparent hover:text-indigo-600 active:text-indigo-500 focus:outline-none focus:ring ml-4") }}
                                </form>
                                <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                    stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M14 5l7 7m0 0l-7 7m7-7H3" />
                                </svg>
                            </button>
                        </div>
                    </div>
                    <!-- Component End  -->
                </div>
{% endblock %}

frontend/templates/studentSearch.html
{% extends "layout.html" %}
{% block content %}
{% for event in userSearchResult %}
            <div class="mt-8 text-gray-500 sm:pr-8 bg-white p-4 shadow-xl hover:shadow-2xl rounded-xl">
                
                <div class="flex flex-col justify-between items-center ">
                    <a href="{{ url_for('main.myProfile', id=event[0] ,tou=typeofuser )}}">
                        <h5 class="text-xl font-bold text-gray-900">{{ event[1] }}</h5>
                    </a>
                    <a href="{{ url_for('main.inbox',to_id=event[0],personName=event[1]) }}">
                        <div class="inline-flex items-center mt-4 text-indigo-600">
                            <p class="text-lg font-medium inline">Message Student</p>

                            <svg xmlns="http://www.w3.org/2000/svg"
                                class="w-6 h-6 ml-3 transition-transform transform group-hover:translate-x-3"
                                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M17 8l4 4m0 0l-4 4m4-4H3" />
                            </svg>
                        </div>
                    </a>
                </div>
                <p class="mt-2 mb-4 text-sm sm:block">
                    Student bio sliced to 15 words
                </p>
                <div class="flex items-center justify-around w-fu">
                    <span
                        class="block border border-green-600 rounded-full px-3 py-1.5 bg-green-100 text-green-600 font-medium text-xs">
                        7 followers
                    </span>

                    <span
                        class="block border bg-orange-100 text-orange-500 border-current px-3 py-1.5 rounded-full text-xs font-medium">
                        17 projects
                    </span>
                </div>

            </div>

            {% endfor %}
            
            
{% endblock %}